[package]
name = "db-qbs-source"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
autobins = false

[[bin]]
name = "db-qbs-source"
path = "src/server_main.rs"

[[bin]]
name = "db-qbs-source-run"
path = "src/main.rs"

[dependencies]
chrono.workspace = true
db-qbs-shared = { path = "../shared" }
libc = "0.2.189"
oracle.workspace = true
rand.workspace = true
rust-embed = { version = "=8.11.0", features = ["debug-embed"] }
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
signal-hook = "0.3.18"
tiny_http.workspace = true
toml.workspace = true
url.workspace = true
ureq.workspace = true
