[package]
name = "db-qbs-sink"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
db-qbs-shared = { path = "../shared" }
mysql = { version = "25.0.1", default-features = false, features = ["minimal-rust"] }
rand.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
tiny_http.workspace = true
toml = "0.8.19"

[dev-dependencies]
db-qbs-source = { path = "../source" }
sqlparser.workspace = true
